version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio_user
      - POSTGRES_PASSWORD=portfolio_password
      - POSTGRES_DB=portfolio_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: portfolio_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: portfolio_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  media_volume: