services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    command: gunicorn core.wsgi:application --config gunicorn.conf.py
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
    expose:
      - 8000
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio_db

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
