# docker-compose.local.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    command: gunicorn core.wsgi:application --config gunicorn.conf.py
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - chromadb

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    ports:
      - "5173:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio_db

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: portfolio_chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE # Optional: disable telemetry

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
  chroma_data:
