name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - migration/django-react-stack
  pull_request:
    branches:
      - main

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          # Use GitHub Secrets for sensitive values
          POSTGRES_DB: ${{ secrets.DB_TEST_NAME }}
          POSTGRES_USER: ${{ secrets.DB_TEST_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          uv venv
          uv sync

      - name: Run linter (Ruff)
        working-directory: ./backend
        run: |
          curl -LsSf https://astral.sh/ruff/install.sh | sh
          ruff check .

      - name: Run formatter check (Ruff)
        working-directory: ./backend
        run: ruff format --check .

      - name: Apply migrations
        working-directory: ./backend
        env:
          DJANGO_SETTINGS_MODULE: core.settings
          DATABASE_URL: postgres://${{ secrets.DB_TEST_USER }}:${{ secrets.DB_TEST_PASSWORD }}@localhost:5432/${{ secrets.DB_TEST_NAME }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}
          DEBUG: "False"
        run: |
          source .venv/bin/activate
          python manage.py migrate

      - name: Set up Django
        working-directory: ./backend
        env:
          DJANGO_SETTINGS_MODULE: core.settings
          DATABASE_URL: postgres://${{ secrets.DB_TEST_USER }}:${{ secrets.DB_TEST_PASSWORD }}@localhost:5432/${{ secrets.DB_TEST_NAME }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}
          DEBUG: "False"
        run: |
          source .venv/bin/activate
          python manage.py check

      - name: Run tests (Pytest)
        working-directory: ./backend
        env:
          DJANGO_SETTINGS_MODULE: core.settings
          DATABASE_URL: postgres://${{ secrets.DB_TEST_USER }}:${{ secrets.DB_TEST_PASSWORD }}@localhost:5432/${{ secrets.DB_TEST_NAME }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}
          DEBUG: "False"
        run: |
          source .venv/bin/activate
          pytest api/tests.py

  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run linter and type check
        working-directory: ./frontend
        run: npm run lint

      - name: Build project
        working-directory: ./frontend
        run: npm run build
